config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  root to: 'pages#index'
  get 'pages/contact'
  get 'pages/about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def contact
  end

  def about
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  
  private
  
  def sign_up_params
    params.require(:user).permit(:email, :password, :password_confirmation, :username, :firstname, :lastname)
  end
  
  def account_update_params
    params.require(:user).permit(:email, :password, :password_confirmation, :current_password, :username, :firstname, :lastname)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_foot.html.erb
<footer class="footer-distributed"> 
   <div class="footer-left"> 
     <h3>Company<span>logo</span></h3> 
     <p class="footer-links">      <a href="#">Home</a>      ·      <a href="#">Blog</a>      ·      <a href="#">Pricing</a>      ·      <a href="#">About</a>      ·      <a href="#">Faq</a>      ·      <a href="#">Contact</a>     </p> 
     <p class="footer-company-name">Company Name &copy; 2015</p> 
     <div class="footer-icons"> 
      <a href="#"><i class="fa fa-facebook"></i></a>      <a href="#"><i class="fa fa-twitter"></i></a>      <a href="#"><i class="fa fa-linkedin"></i></a>      <a href="#"><i class="fa fa-github"></i></a> 
    </div> 
 
   </div> 
 
   <div class="footer-right"> 

    <p>Contact Us</p> 

    <form action="#" method="post"> 
     <input type="text" name="email" placeholder="Email" />      <textarea name="message" placeholder="Message"></textarea>      <button>Send</button> 
    </form> 

   </div> 
 
  </footer>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">

  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Kevin Learns", root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'About', pages_about_path %></li>
        
        <li><%= link_to 'Contact Us', pages_contact_path %></li>
        
        <% if !current_user %>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          <li><%= link_to 'Sign In', new_user_session_path %></li>

        <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><% current_user.username %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% end %>
        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->

</nav> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kevin Lears</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    


    <%= render 'layouts/nav' %>
    
    <%= bootstrap_flash %>
    
    <div class='container'>
      <%= yield %>
    </div>
    
    <%= render 'layouts/foot' %>

  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>